DROP TABLE IF EXISTS POSTS;

CREATE TABLE POSTS (
    NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NULL,
    VIEWS INT DEFAULT 0
);
